[package]
name = "airdrop"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
hex = "0.4.3"
soroban-sdk = { workspace = true, features = ["testutils"] }
